//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRentApp_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apartmani
    {
        public int id { get; set; }
        public string naziv { get; set; }
        public string opis { get; set; }
        public string slikaURL { get; set; }
        public Nullable<decimal> cijena { get; set; }
        public Nullable<int> ocijena { get; set; }
        public string Grad { get; set; }
        public string Adresa { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public string SEO_Url { get; set; }
    }
}
